Repository Grant-Nelson/ThreeDart, pull requests merged in 2018-10, with the labels that each got.

#66 Chunk opt and fix
  web/examples/craft/chunk.dart
  web/examples/craft/constants.dart
  web/examples/craft/generator.dart
  web/examples/craft/main.dart
  web/examples/craft/player.dart
  web/examples/craft/shaper.dart
  web/examples/craft/world.dart
Labels: enhancement

#70 Hypersphere example
  lib/src/Shaders/Inspection.dart
  lib/src/Techniques/Inspection.dart
  lib/src/Views/BackTarget.dart
  lib/src/Views/Perspective.dart
  web/examples/hypersphere/index.html
  web/examples/hypersphere/main.dart
  web/examples/hypersphere/projection.dart
  web/examples/hypersphere/slice.dart
  web/main.dart
  web/tests/test028/test.dart
Labels: Hacktoberfest, enhancement

#72 Updated the hypersphere example
  lib/src/Shapes/Builders.dart
  lib/src/Techniques/Inspection.dart
  web/examples/hypersphere/example2D.dart
  web/examples/hypersphere/example3D.dart
  web/examples/hypersphere/example4D.dart
  web/examples/hypersphere/main.dart
  web/examples/hypersphere/projection.dart
  web/examples/hypersphere/slice.dart
Labels: Hacktoberfest, Medium, enhancement

#76 Added shader printouts and event once
  lib/src/Core/ThreeDart.dart
  lib/src/Events/Event.dart
  lib/src/Shaders/Shader.dart
  lib/src/Techniques/Depth.dart
  lib/src/Techniques/Distort.dart
  lib/src/Techniques/GaussianBlur.dart
  lib/src/Techniques/MaterialLight.dart
  lib/src/Techniques/Normal.dart
  lib/src/Techniques/Skybox.dart
  web/common/glslParser.dart
  web/tests/test001/test.dart
  web/tests/test003/test.dart
  web/tests/test004/test.dart
  web/tests/test005/test.dart
  web/tests/test006/test.dart
  web/tests/test007/test.dart
  web/tests/test008/BumpyTechnique.dart
  web/tests/test008/test.dart
  web/tests/test009/test.dart
  web/tests/test010/test.dart
  web/tests/test011/test.dart
  web/tests/test012/test.dart
  web/tests/test013/test.dart
  web/tests/test014/test.dart
  web/tests/test015/test.dart
  web/tests/test016/test.dart
  web/tests/test017/test.dart
  web/tests/test018/test.dart
  web/tests/test019/test.dart
  web/tests/test020/test.dart
  web/tests/test021/test.dart
  web/tests/test022/test.dart
  web/tests/test023/test.dart
  web/tests/test024/test.dart
  web/tests/test025/test.dart
  web/tests/test026/test.dart
  web/tests/test027/test.dart
  web/tests/test028/test.dart
  web/tests/test029/test.dart
  web/tests/test030/test.dart
  web/tests/test037/test.dart
Labels: Hacktoberfest, Medium, enhancement

#74 Init world from seed query param.
  web/examples/craft/main.dart
  web/examples/craft/world.dart
Labels: Hacktoberfest, Small, enhancement

#77 Touch up to randomizer
  web/examples/craft/constants.dart
  web/examples/craft/main.dart
Labels: Hacktoberfest, Small, enhancement

#78 Fixed mouse movements in Hypercube
  web/examples/hypersphere/example2D.dart
  web/examples/hypersphere/example3D.dart
  web/examples/hypersphere/example4D.dart
Labels: Hacktoberfest, Small, bug

#80 Better Blur
  lib/src/Shaders/GaussianBlur.dart
  web/tests/test028/test.dart
  web/tests/test040/test.dart
  web/tests/test040/test.png
  web/tests/test041/index.html
  web/tests/test041/test.dart
  web/tests/test041/test.png
Labels: Hacktoberfest, Small, enhancement
